### PR TITLE
Create a simple tools menu to make CP development a bit quicker

### PR DESCRIPTION
**Pull request by macta**
Creates a simple Paradise tools menu - does rely on having BaselineOfCPEnvironment created so that it can identify the sqeakjs resource

### CODE REVIEW

**Comment by ErikOnBike** [comment]
Tim,

Could you please move the class CpDevTools to package/tag 'CodeParadise-WebApplication-DevTools'?
It is solely based on the WebApplication package. The Beach package is meant for a set of UI components.

Apart from that: I love it! :-)

Cheers,
Erik

**Comment by macta** [comment]
I've applied the change requested

**Comment by macta** [comment]
Having moved it however, I wonder if there should be a completely optional Dev package that can be loaded on top - as DevTools isn't required for deployment

**Comment by ErikOnBike** [comment]
I do agree on package being optional. We'll make it optional later ;-).

**Pull request merged**
